### ISSUE TITLE
Idea: group related properties together in shorthands

### ISSUE THREAD

**Issue by tesseralis** [components-ai/css.gui#353]
There are some properties that seem like they should be part of shorthands but aren't:

* [`text-decoration-skip-ink`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-skip-ink)
* [`background-blend-mode`](https://developer.mozilla.org/en-US/docs/Web/CSS/background-blend-mode)

It might be worthwhile to still treat those inputs as part of the shorthand input in our UI, and generate the separated UI. So a style object like:

```js
{
  color: '#ff00ff',
  line: 'underline',
  style: 'solid',
  thickness: '1px',
  skipInk: 'all',
}
```

would generate the style:

```css
.my-style {
  text-decoration: #ff00ff underline solid 1px;
  text-decoration-skip-ink: all;
}
```

This is especially helpful for something like `background-blend-mode`, which is an array property that can get confusing to keep track off when edited separately from the main `background` property
